on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable, 1.39.0]

        # The default target we're compiling on and for
        TARGET: [thumbv6m-none-eabi, thumbv7m-none-eabi, thumbv7em-none-eabi, thumbv7em-none-eabihf, thumbv8m.main-none-eabi]

        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true

    steps:
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '7-2018-q2'
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
          components: rustfmt
      - name: Install qemu
        run: sudo apt-get install qemu-system-arm
      - name: Run CI script for ${{ matrix.TARGET }} under ${{ matrix.rust }}
        run: TARGET=${{ matrix.TARGET }} bash ci/script.sh
